version: '2'

services:

  pulsar:
    image: apachepulsar/pulsar
    ports:
      - "8080:8080"
      - "6650:6650"
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && exec bin/pulsar standalone --advertised-address pulsar
      && curl -XPUT localhost:8080/admin/v2/persistent/pulsar/ns1/key_shared-topic
      && curl -XPUT localhost:8080/admin/v2/persistent/pulsar/ns1/shared-topic" 

  prometheus:
    image: prom/prometheus
    depends_on:
      - pulsar
    volumes:
      - ./standalone.prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  pulsar-grafana:
    image: apachepulsar/pulsar-grafana:latest
    depends_on:
      - pulsar
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - PROMETHEUS_URL=http://prometheus:9090/
      - PULSAR_PROMETHEUS_URL=http://prometheus:9090/
      - PULSAR_CLUSTER=standalone

#  pulsar-dashboard:
#    image: apachepulsar/pulsar-dashboard
#    depends_on:
#      - pulsar
#    ports:
#      - "7777:80"
#    environment:
#      - SERVICE_URL=http://pulsar:8080

