version: '2'

services:

  pulsar:
    image: apachepulsar/pulsar
    ports:
      - "8180:8080"
      - "6650:6650"
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && exec bin/pulsar standalone --advertised-address pulsar
      && curl -XPUT localhost:8080/admin/v2/persistent/pulsar/ns1/key_shared-topic
      && curl -XPUT localhost:8080/admin/v2/persistent/pulsar/ns1/shared-topic" 

  pulsar-dashboard:
    image: apachepulsar/pulsar-dashboard
    depends_on:
      - pulsar
    ports:
      - "9090:80"
    environment:
      - SERVICE_URL=http://pulsar:8080

  producer:
    image: nacho270/apache-pulsar-demo-producer
    ports:
      - "7070:7070"
    depends_on:
      - pulsar
    environment:
      - PULSAR_URL=pulsar://pulsar:6650
      - PULSAR_ADMIN=pulsar://pulsar:8180

  consumer-1:
    image: nacho270/apache-pulsar-demo-consumer
    ports:
      - "8280:8080"
    depends_on:
      - pulsar
    environment:
      - PULSAR_URL=pulsar://pulsar:6650
      - PULSAR_ADMIN=pulsar://pulsar:8180

  consumer-2:
    image: nacho270/apache-pulsar-demo-consumer
    ports:
      - "8380:8080"
    depends_on:
      - pulsar
    environment:
      - PULSAR_URL=pulsar://pulsar:6650
      - PULSAR_ADMIN=pulsar://pulsar:8180
